language: node_js
node_js:
  - "0.11"
#  - "0.10"
#  - "0.8"
#  - "0.6"

before_script:
#  - rackup  # start a Web server (Ruby)
  - npm start   # Fork a Web server (Node)
  - sleep 3  # give Web server some time to bind to sockets, etc

script:
  - grunt
  - npm test

#after_script:
#  - ps aux | grep node
#  - kill PID
